/**
 * Barrel for app constants. Re-exports the full shared constant set (categories,
 * niches, contentTypes, platforms, rewards, statuses, reports — incl. the
 * `canTransitionCampaign` helper and every status union) plus the local design
 * tokens. App code should `import { CATEGORIES, LIGHT, RADII } from '@/constants'`.
 *
 * The shared constants come from `../_shared` — an in-project mirror of the
 * monorepo's `app/shared` workspace, generated by `scripts/sync-shared.js` so
 * Metro can bundle it (see that script + `metro.config.js` for why).
 */
export * from '../_shared/constants';
export * from './theme';
