/**
 * Metro config.
 *
 * NativeWind — compile `global.css` (Tailwind utilities) into the bundle.
 *
 * Monorepo note: the app consumes the shared domain types/constants (`app/shared`)
 * via an in-project mirror at `app/mobile/_shared` (generated by
 * `scripts/sync-shared.js`, imported through the `@/constants` and `@/types`
 * barrels). The mirror lives under the project root so Metro's crawler indexes it
 * normally — no `watchFolders` across the project boundary, which Metro's file
 * crawler does not reliably index on Windows. See `scripts/sync-shared.js`.
 */
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' });
