/**
 * Barrel for app domain types. Re-exports every shared interface (User,
 * BusinessProfile, CreatorProfile, Campaign, Application, Notification, Report,
 * and the `common` sub-types).
 *
 * Sourced from `../_shared` — an in-project mirror of the monorepo's `app/shared`
 * workspace, generated by `scripts/sync-shared.js` so Metro can bundle it.
 */
export * from '../_shared/types';
